prjLesson/Models/Members.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjLesson.Models
{
    public partial class Members
    {
        public int MemberId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public int? Age { get; set; }
        public string FileName { get; set; }
        public byte[] FileData { get; set; }
    }
}

prjLesson/Controllers/ApiController.cs
using Microsoft.AspNetCore.Mvc;
using prjLesson.Models;
using System.Text;

namespace prjLesson.Controllers
{
    public class ApiController : Controller
    {
        private readonly DemoContext _context;
        private readonly IWebHostEnvironment _host;

        public ApiController(DemoContext context, IWebHostEnvironment host){
            _context = context;
            _host = host;
        }

        public IActionResult Index(string name, int age = 20)
        {
            if (string.IsNullOrEmpty(name))
            {
                name = "Guest";
            }
            return Content($"Hello {name}!! You're {age} years old now!!");
            //return Content("Hello Ajax");
            //return Content("<h2>Hello Content</h2>", "text/html");
            //return Content("<h2>Hello Content 好好好</h2>", "text/html", Encoding.UTF8);

            //return Content("Index", "application/msword");
        }

        public IActionResult AjaxEvent(string userName)
        {
            if(string.IsNullOrEmpty(userName))
            {
                userName = "Guest";
            }

            System.Threading.Thread.Sleep(5000);
            return Content("Hello " +  userName);
        }

        [HttpPost]
        public IActionResult Register(Members member, IFormFile photo) 
        {
            string result = "未上傳檔案";
            if (photo != null)
            {
                string photoName = Path.GetFileNameWithoutExtension(photo.FileName) + Guid.NewGuid().GetHashCode() + Path.GetExtension(photo.FileName);
                result = Path.Combine(_host.WebRootPath, "uploads", photoName);
                using (var fileStream = new FileStream(result, FileMode.Create))
                {
                    photo.CopyTo(fileStream);
                }

                byte[]? imgByte = null;
                using(var memoryStream = new MemoryStream())
                {
                    photo.CopyTo(memoryStream);
                    imgByte = memoryStream.ToArray();
                }

                //加入資料庫
                member.FileName = photoName;
                member.FileData = imgByte;
                _context.Members.Add(member);
                _context.SaveChanges();
            }

            return Content(result);
            //return Content($"Hello {member.Name}");
        }

        public IActionResult GetImage(int id = 1)
        {
            Members? member = _context.Members.Find(id);
            byte[]? imgByte = null;
            if(member != null)
            {
                imgByte = member.FileData;
            }

            return File(imgByte, "image/jpeg");
        }

        public IActionResult Cities()
        {
            var cities = _context.Address.Select(x => x.City).Distinct();

            return Json(cities);
        }

        public IActionResult Districts(string city) 
        {
            var districts = _context.Address.Where(x=> x.City == city).Select(x=> x.SiteId).Distinct();

            return Json(districts);
        }

        public IActionResult Roads(string district) 
        {
            var roads = _context.Address.Where(x=>x.SiteId == district).Select(x=>x.Road).Distinct();

            return Json(roads);
        }

        public IActionResult Address()
        {
            var addressDict = new Dictionary<object, Dictionary<object, List<object>>>();
            
            foreach(var address in _context.Address)
            {
                if (addressDict.ContainsKey(address.City))
                {
                    if (addressDict[address.City].ContainsKey(address.SiteId))
                    {
                        addressDict[address.City][address.SiteId].Add(address.Road);
                        
                    }
                    else
                    {
                        addressDict[address.City].Add(address.SiteId, new List<object>() { address.Road});
                    }
                }
                else
                {
                    addressDict.Add(address.City, new Dictionary<object, List<object>> { { address.SiteId, new List<object> { address.Road} } });
                }
            }

            return Json(addressDict.ToArray());
        }

        //public IActionResult Addresss()
        //{
        //    var addressList = new List<string>();
        //    foreach (var address in _context.Address)
        //    {
        //        if (addressList.Contains(address.City))
        //        {
        //            if(addressList.Contains)
        //        }
        //    }
        //}
    }
}

prjLesson/Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using prjLesson.Models;

namespace prjLesson.Controllers
{
    public class MembersController : Controller
    {
        private readonly DemoContext _context;

        public MembersController(DemoContext context)
        {
            _context = context;
        }

        // GET: Members
        public async Task<IActionResult> Index()
        {
              return _context.Members != null ? 
                          View(await _context.Members.ToListAsync()) :
                          Problem("Entity set 'DemoContext.Members'  is null.");
        }

        // GET: Members/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Members == null)
            {
                return NotFound();
            }

            var members = await _context.Members
                .FirstOrDefaultAsync(m => m.MemberId == id);
            if (members == null)
            {
                return NotFound();
            }

            return View(members);
        }

        // GET: Members/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Members/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MemberId,Name,Email,Age,FileName,FileData")] Members members)
        {
            if (ModelState.IsValid)
            {
                _context.Add(members);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(members);
        }

        // GET: Members/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Members == null)
            {
                return NotFound();
            }

            var members = await _context.Members.FindAsync(id);
            if (members == null)
            {
                return NotFound();
            }
            return View(members);
        }

        // POST: Members/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MemberId,Name,Email,Age,FileName,FileData")] Members members)
        {
            if (id != members.MemberId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(members);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MembersExists(members.MemberId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(members);
        }

        // GET: Members/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Members == null)
            {
                return NotFound();
            }

            var members = await _context.Members
                .FirstOrDefaultAsync(m => m.MemberId == id);
            if (members == null)
            {
                return NotFound();
            }

            return View(members);
        }

        // POST: Members/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Members == null)
            {
                return Problem("Entity set 'DemoContext.Members'  is null.");
            }
            var members = await _context.Members.FindAsync(id);
            if (members != null)
            {
                _context.Members.Remove(members);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MembersExists(int id)
        {
          return (_context.Members?.Any(e => e.MemberId == id)).GetValueOrDefault();
        }
    }
}

prjLesson/Views/Members/Create.cshtml
@model prjLesson.Models.Members

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Members</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MemberId" class="control-label"></label>
                <input asp-for="MemberId" class="form-control" />
                <span asp-validation-for="MemberId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FileName" class="control-label"></label>
                <input asp-for="FileName" class="form-control" />
                <span asp-validation-for="FileName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FileData" class="control-label"></label>
                <input asp-for="FileData" class="form-control" />
                <span asp-validation-for="FileData" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

prjLesson/Views/Members/Delete.cshtml
@model prjLesson.Models.Members

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Members</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FileName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FileName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FileData)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FileData)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MemberId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

prjLesson/Views/Members/Details.cshtml
@model prjLesson.Models.Members

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Members</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FileName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FileName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FileData)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FileData)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.MemberId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

prjLesson/Views/Members/Edit.cshtml
@model prjLesson.Models.Members

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Members</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MemberId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FileName" class="control-label"></label>
                <input asp-for="FileName" class="form-control" />
                <span asp-validation-for="FileName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FileData" class="control-label"></label>
                <input asp-for="FileData" class="form-control" />
                <span asp-validation-for="FileData" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

prjLesson/Views/Members/Index.cshtml
@model IEnumerable<prjLesson.Models.Members>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FileName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FileData)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Age)
                </td>
                <td>
                    @*@Html.DisplayFor(modelItem => item.FileName)*@
                    <img src="~/uploads/@item.FileName" class="img-thumbnail" />
                </td>
                <td>
                    @*@Html.DisplayFor(modelItem => item.FileData)*@
                    <img src="~/Api/GetImage/@item.MemberId" class="img-thumbnail" />

                    <img src="@Url.Action("GetImage", "Api", new {Id = item.MemberId})" class="img-thumbnail" />
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.MemberId">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.MemberId">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.MemberId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>